-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity normalize_0_0_0_0_0_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of normalize_0_0_0_0_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv21_7E000 : STD_LOGIC_VECTOR (20 downto 0) := "001111110000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal p_Val2_4_fu_42_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_2811_4_cast_cast_fu_50_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Val2_11_4_fu_54_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_31_fu_60_p4 : STD_LOGIC_VECTOR (10 downto 0);


begin



    ap_ready <= ap_const_logic_1;
        ap_return <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_31_fu_60_p4),16));

    p_Val2_11_4_fu_54_p2 <= std_logic_vector(signed(tmp_2811_4_cast_cast_fu_50_p1) + signed(ap_const_lv21_7E000));
    p_Val2_4_fu_42_p3 <= (data_4_V_read & ap_const_lv4_0);
        tmp_2811_4_cast_cast_fu_50_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_4_fu_42_p3),21));

    tmp_31_fu_60_p4 <= p_Val2_11_4_fu_54_p2(20 downto 10);
end behav;
