-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity normalize_0_0_0_0_0_1 is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_17_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of normalize_0_0_0_0_0_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv21_190000 : STD_LOGIC_VECTOR (20 downto 0) := "110010000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv20_54000 : STD_LOGIC_VECTOR (19 downto 0) := "01010100000000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv20_FC000 : STD_LOGIC_VECTOR (19 downto 0) := "11111100000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_5_fu_104_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Val2_2_fu_118_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_3311_2_cast_cast_fu_126_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Val2_13_2_fu_130_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_28_fu_136_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_5_fu_150_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_3311_5_cast_cast_fu_158_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_13_5_fu_162_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_29_fu_168_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_fu_182_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Val2_s_fu_196_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_3311_cast_cast_fu_204_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_13_s_fu_208_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_30_fu_214_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_9_fu_228_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal res_0_V_write_assig_fu_114_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_2_V_write_assig_fu_146_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_5_V_write_assig_fu_178_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_9_V_write_assig_fu_192_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_14_V_write_assi_fu_224_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_17_V_write_assi_fu_238_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= res_0_V_write_assig_fu_114_p1;
    ap_return_1 <= res_2_V_write_assig_fu_146_p1;
    ap_return_2 <= res_5_V_write_assig_fu_178_p1;
    ap_return_3 <= res_9_V_write_assig_fu_192_p1;
    ap_return_4 <= res_14_V_write_assi_fu_224_p1;
    ap_return_5 <= res_17_V_write_assi_fu_238_p1;
    p_Val2_13_2_fu_130_p2 <= std_logic_vector(signed(tmp_3311_2_cast_cast_fu_126_p1) + signed(ap_const_lv21_190000));
    p_Val2_13_5_fu_162_p2 <= std_logic_vector(signed(tmp_3311_5_cast_cast_fu_158_p1) + signed(ap_const_lv20_54000));
    p_Val2_13_s_fu_208_p2 <= std_logic_vector(signed(tmp_3311_cast_cast_fu_204_p1) + signed(ap_const_lv20_FC000));
    p_Val2_2_fu_118_p3 <= (data_2_V_read & ap_const_lv4_0);
    p_Val2_5_fu_150_p3 <= (data_5_V_read & ap_const_lv3_0);
    p_Val2_s_fu_196_p3 <= (data_14_V_read & ap_const_lv3_0);
        res_0_V_write_assig_fu_114_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_104_p4),16));

        res_14_V_write_assi_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_30_fu_214_p4),16));

        res_17_V_write_assi_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_fu_228_p4),16));

        res_2_V_write_assig_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_28_fu_136_p4),16));

    res_5_V_write_assig_fu_178_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_29_fu_168_p4),16));
        res_9_V_write_assig_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_182_p4),16));

    tmp_28_fu_136_p4 <= p_Val2_13_2_fu_130_p2(20 downto 10);
    tmp_29_fu_168_p4 <= p_Val2_13_5_fu_162_p2(19 downto 10);
    tmp_30_fu_214_p4 <= p_Val2_13_s_fu_208_p2(19 downto 10);
        tmp_3311_2_cast_cast_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_2_fu_118_p3),21));

        tmp_3311_5_cast_cast_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_5_fu_150_p3),20));

        tmp_3311_cast_cast_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_s_fu_196_p3),20));

    tmp_5_fu_104_p4 <= data_0_V_read(15 downto 9);
    tmp_7_fu_182_p4 <= data_9_V_read(15 downto 9);
    tmp_9_fu_228_p4 <= data_17_V_read(15 downto 10);
end behav;
