-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity normalize_0_0 is
port (
    ap_ready : OUT STD_LOGIC;
    data_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of normalize_0_0 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv24_378000 : STD_LOGIC_VECTOR (23 downto 0) := "001101111000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal p_Val2_s_fu_44_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp4_cast_cast_fu_52_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_1_fu_56_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_32_fu_62_p4 : STD_LOGIC_VECTOR (13 downto 0);


begin



    ap_ready <= ap_const_logic_1;
        ap_return <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_32_fu_62_p4),16));

    p_Val2_1_fu_56_p2 <= std_logic_vector(signed(tmp4_cast_cast_fu_52_p1) + signed(ap_const_lv24_378000));
    p_Val2_s_fu_44_p3 <= (data_V_read & ap_const_lv7_0);
        tmp4_cast_cast_fu_52_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_s_fu_44_p3),24));

    tmp_32_fu_62_p4 <= p_Val2_1_fu_56_p2(23 downto 10);
end behav;
