-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity normalize_0_0_0_0_0_2 is
port (
    ap_ready : OUT STD_LOGIC;
    data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_13_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_15_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_20_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of normalize_0_0_0_0_0_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv20_FE000 : STD_LOGIC_VECTOR (19 downto 0) := "11111110000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv21_14C000 : STD_LOGIC_VECTOR (20 downto 0) := "101001100000000000000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal p_Val2_1_fu_112_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_3811_1_cast_cast_fu_120_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_15_1_fu_124_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_25_fu_130_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_fu_144_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_158_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_s_fu_172_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_3811_cast_cast_fu_180_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Val2_15_s_fu_184_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_26_fu_190_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_204_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_218_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Val2_2_fu_232_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_3811_2_cast_cast_fu_240_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Val2_15_2_fu_244_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_27_fu_250_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal res_1_V_write_assig_fu_140_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_3_V_write_assig_fu_154_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_7_V_write_assig_fu_168_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_13_V_write_assi_fu_200_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_14_V_write_assi_fu_214_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_15_V_write_assi_fu_228_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_20_V_write_assi_fu_260_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= res_1_V_write_assig_fu_140_p1;
    ap_return_1 <= res_3_V_write_assig_fu_154_p1;
    ap_return_2 <= res_7_V_write_assig_fu_168_p1;
    ap_return_3 <= res_13_V_write_assi_fu_200_p1;
    ap_return_4 <= res_14_V_write_assi_fu_214_p1;
    ap_return_5 <= res_15_V_write_assi_fu_228_p1;
    ap_return_6 <= res_20_V_write_assi_fu_260_p1;
    p_Val2_15_1_fu_124_p2 <= std_logic_vector(signed(tmp_3811_1_cast_cast_fu_120_p1) + signed(ap_const_lv20_FE000));
    p_Val2_15_2_fu_244_p2 <= std_logic_vector(signed(tmp_3811_2_cast_cast_fu_240_p1) + signed(ap_const_lv20_FE000));
    p_Val2_15_s_fu_184_p2 <= std_logic_vector(signed(tmp_3811_cast_cast_fu_180_p1) + signed(ap_const_lv21_14C000));
    p_Val2_1_fu_112_p3 <= (data_1_V_read & ap_const_lv3_0);
    p_Val2_2_fu_232_p3 <= (data_20_V_read & ap_const_lv3_0);
    p_Val2_s_fu_172_p3 <= (data_13_V_read & ap_const_lv3_0);
        res_13_V_write_assi_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_26_fu_190_p4),16));

        res_14_V_write_assi_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_204_p4),16));

        res_15_V_write_assi_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_218_p4),16));

        res_1_V_write_assig_fu_140_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_25_fu_130_p4),16));

        res_20_V_write_assi_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_27_fu_250_p4),16));

        res_3_V_write_assig_fu_154_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_144_p4),16));

        res_7_V_write_assig_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_158_p4),16));

    tmp_25_fu_130_p4 <= p_Val2_15_1_fu_124_p2(19 downto 10);
    tmp_26_fu_190_p4 <= p_Val2_15_s_fu_184_p2(20 downto 10);
    tmp_27_fu_250_p4 <= p_Val2_15_2_fu_244_p2(19 downto 10);
    tmp_2_fu_158_p4 <= data_7_V_read(15 downto 7);
        tmp_3811_1_cast_cast_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_1_fu_112_p3),20));

        tmp_3811_2_cast_cast_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_2_fu_232_p3),20));

        tmp_3811_cast_cast_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_s_fu_172_p3),21));

    tmp_3_fu_204_p4 <= data_14_V_read(15 downto 8);
    tmp_4_fu_218_p4 <= data_15_V_read(15 downto 9);
    tmp_s_fu_144_p4 <= data_3_V_read(15 downto 7);
end behav;
