-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity relu is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_17_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (13 downto 0) );
end;


architecture behav of relu is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_19_fu_98_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_106_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_4_fu_88_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_8_fu_82_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_fu_110_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_0_V_write_assig_fu_116_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_20_fu_144_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_2_fu_152_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_9_fu_134_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_8_2_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_2_fu_156_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_2_V_write_assig_fu_162_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_21_fu_190_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_5_fu_198_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_2_fu_180_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_8_5_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_5_fu_202_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_5_V_write_assig_fu_208_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_22_fu_236_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_9_fu_244_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_6_fu_226_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_8_9_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_9_fu_248_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_9_V_write_assig_fu_254_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_23_fu_282_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_s_fu_290_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_fu_272_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_8_s_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_s_fu_294_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_14_V_write_assi_fu_300_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_24_fu_328_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_1_fu_336_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_1_fu_318_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_8_1_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_1_fu_340_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_17_V_write_assi_fu_346_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_0_V_write_assig_1_fu_124_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_2_V_write_assig_1_fu_170_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_5_V_write_assig_1_fu_216_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_9_V_write_assig_1_fu_262_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_14_V_write_assi_2_fu_308_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_17_V_write_assi_1_fu_354_p1 : STD_LOGIC_VECTOR (13 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= res_0_V_write_assig_1_fu_124_p1;
    ap_return_1 <= res_2_V_write_assig_1_fu_170_p1;
    ap_return_2 <= res_5_V_write_assig_1_fu_216_p1;
    ap_return_3 <= res_9_V_write_assig_1_fu_262_p1;
    ap_return_4 <= res_14_V_write_assi_2_fu_308_p1;
    ap_return_5 <= res_17_V_write_assi_1_fu_354_p1;
    p_Val2_4_1_fu_340_p2 <= std_logic_vector(unsigned(tmp_11_1_fu_336_p1) + unsigned(tmp_1_fu_318_p4));
    p_Val2_4_2_fu_156_p2 <= std_logic_vector(unsigned(tmp_11_2_fu_152_p1) + unsigned(tmp_9_fu_134_p4));
    p_Val2_4_5_fu_202_p2 <= std_logic_vector(unsigned(tmp_11_5_fu_198_p1) + unsigned(tmp_2_fu_180_p4));
    p_Val2_4_9_fu_248_p2 <= std_logic_vector(unsigned(tmp_11_9_fu_244_p1) + unsigned(tmp_6_fu_226_p4));
    p_Val2_4_fu_110_p2 <= std_logic_vector(unsigned(tmp_s_fu_106_p1) + unsigned(tmp_4_fu_88_p4));
    p_Val2_4_s_fu_294_p2 <= std_logic_vector(unsigned(tmp_11_s_fu_290_p1) + unsigned(tmp_7_fu_272_p4));
    res_0_V_write_assig_1_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_0_V_write_assig_fu_116_p3),14));
    res_0_V_write_assig_fu_116_p3 <= 
        p_Val2_4_fu_110_p2 when (tmp_8_fu_82_p2(0) = '1') else 
        ap_const_lv13_0;
    res_14_V_write_assi_2_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_14_V_write_assi_fu_300_p3),14));
    res_14_V_write_assi_fu_300_p3 <= 
        p_Val2_4_s_fu_294_p2 when (tmp_8_s_fu_266_p2(0) = '1') else 
        ap_const_lv13_0;
    res_17_V_write_assi_1_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_17_V_write_assi_fu_346_p3),14));
    res_17_V_write_assi_fu_346_p3 <= 
        p_Val2_4_1_fu_340_p2 when (tmp_8_1_fu_312_p2(0) = '1') else 
        ap_const_lv13_0;
    res_2_V_write_assig_1_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_2_V_write_assig_fu_162_p3),14));
    res_2_V_write_assig_fu_162_p3 <= 
        p_Val2_4_2_fu_156_p2 when (tmp_8_2_fu_128_p2(0) = '1') else 
        ap_const_lv13_0;
    res_5_V_write_assig_1_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_5_V_write_assig_fu_208_p3),14));
    res_5_V_write_assig_fu_208_p3 <= 
        p_Val2_4_5_fu_202_p2 when (tmp_8_5_fu_174_p2(0) = '1') else 
        ap_const_lv13_0;
    res_9_V_write_assig_1_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_9_V_write_assig_fu_254_p3),14));
    res_9_V_write_assig_fu_254_p3 <= 
        p_Val2_4_9_fu_248_p2 when (tmp_8_9_fu_220_p2(0) = '1') else 
        ap_const_lv13_0;
    tmp_11_1_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_328_p3),13));
    tmp_11_2_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_fu_144_p3),13));
    tmp_11_5_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_21_fu_190_p3),13));
    tmp_11_9_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_22_fu_236_p3),13));
    tmp_11_s_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_23_fu_282_p3),13));
    tmp_19_fu_98_p3 <= data_0_V_read(2 downto 2);
    tmp_1_fu_318_p4 <= data_17_V_read(15 downto 3);
    tmp_20_fu_144_p3 <= data_2_V_read(2 downto 2);
    tmp_21_fu_190_p3 <= data_5_V_read(2 downto 2);
    tmp_22_fu_236_p3 <= data_9_V_read(2 downto 2);
    tmp_23_fu_282_p3 <= data_14_V_read(2 downto 2);
    tmp_24_fu_328_p3 <= data_17_V_read(2 downto 2);
    tmp_2_fu_180_p4 <= data_5_V_read(15 downto 3);
    tmp_4_fu_88_p4 <= data_0_V_read(15 downto 3);
    tmp_6_fu_226_p4 <= data_9_V_read(15 downto 3);
    tmp_7_fu_272_p4 <= data_14_V_read(15 downto 3);
    tmp_8_1_fu_312_p2 <= "1" when (signed(data_17_V_read) > signed(ap_const_lv16_0)) else "0";
    tmp_8_2_fu_128_p2 <= "1" when (signed(data_2_V_read) > signed(ap_const_lv16_0)) else "0";
    tmp_8_5_fu_174_p2 <= "1" when (signed(data_5_V_read) > signed(ap_const_lv16_0)) else "0";
    tmp_8_9_fu_220_p2 <= "1" when (signed(data_9_V_read) > signed(ap_const_lv16_0)) else "0";
    tmp_8_fu_82_p2 <= "1" when (signed(data_0_V_read) > signed(ap_const_lv16_0)) else "0";
    tmp_8_s_fu_266_p2 <= "1" when (signed(data_14_V_read) > signed(ap_const_lv16_0)) else "0";
    tmp_9_fu_134_p4 <= data_2_V_read(15 downto 3);
    tmp_s_fu_106_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_fu_98_p3),13));
end behav;
