-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity relu is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_8_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_10_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_11_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_12_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_13_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_14_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_15_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_16_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_17_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_18_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_19_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_20_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    data_21_V_read : IN STD_LOGIC_VECTOR (16 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (16 downto 0) );
end;


architecture behav of relu is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_3_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_206_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_0_V_write_assig_fu_210_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_1_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_228_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_1_V_write_assig_fu_232_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_2_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_250_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_2_V_write_assig_fu_254_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_3_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_fu_272_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_3_V_write_assig_fu_276_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_4_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_294_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_4_V_write_assig_fu_298_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_5_fu_310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_fu_316_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_5_V_write_assig_fu_320_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_6_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_fu_338_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_6_V_write_assig_fu_342_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_7_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_fu_360_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_7_V_write_assig_fu_364_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_8_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_46_fu_382_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_8_V_write_assig_fu_386_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_9_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_fu_404_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_9_V_write_assig_fu_408_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_s_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_fu_426_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_10_V_write_assi_fu_430_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_10_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_448_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_11_V_write_assi_fu_452_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_11_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_470_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_12_V_write_assi_fu_474_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_12_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_fu_492_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_13_V_write_assi_fu_496_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_13_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_514_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_14_V_write_assi_fu_518_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_14_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_53_fu_536_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_15_V_write_assi_fu_540_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_15_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_fu_558_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_16_V_write_assi_fu_562_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_16_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_fu_580_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_17_V_write_assi_fu_584_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_17_fu_596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_56_fu_602_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_18_V_write_assi_fu_606_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_18_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_fu_624_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_19_V_write_assi_fu_628_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_19_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_fu_646_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_20_V_write_assi_fu_650_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_20_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_fu_668_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_21_V_write_assi_fu_672_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_0_V_write_assig_3_fu_218_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_1_V_write_assig_3_fu_240_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_2_V_write_assig_3_fu_262_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_3_V_write_assig_3_fu_284_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_4_V_write_assig_3_fu_306_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_5_V_write_assig_3_fu_328_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_6_V_write_assig_3_fu_350_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_7_V_write_assig_3_fu_372_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_8_V_write_assig_2_fu_394_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_9_V_write_assig_2_fu_416_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_10_V_write_assi_2_fu_438_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_11_V_write_assi_2_fu_460_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_12_V_write_assi_2_fu_482_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_13_V_write_assi_2_fu_504_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_14_V_write_assi_2_fu_526_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_15_V_write_assi_2_fu_548_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_16_V_write_assi_2_fu_570_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_17_V_write_assi_2_fu_592_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_18_V_write_assi_2_fu_614_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_19_V_write_assi_2_fu_636_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_20_V_write_assi_2_fu_658_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_21_V_write_assi_1_fu_680_p1 : STD_LOGIC_VECTOR (16 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= res_0_V_write_assig_3_fu_218_p1;
    ap_return_1 <= res_1_V_write_assig_3_fu_240_p1;
    ap_return_10 <= res_10_V_write_assi_2_fu_438_p1;
    ap_return_11 <= res_11_V_write_assi_2_fu_460_p1;
    ap_return_12 <= res_12_V_write_assi_2_fu_482_p1;
    ap_return_13 <= res_13_V_write_assi_2_fu_504_p1;
    ap_return_14 <= res_14_V_write_assi_2_fu_526_p1;
    ap_return_15 <= res_15_V_write_assi_2_fu_548_p1;
    ap_return_16 <= res_16_V_write_assi_2_fu_570_p1;
    ap_return_17 <= res_17_V_write_assi_2_fu_592_p1;
    ap_return_18 <= res_18_V_write_assi_2_fu_614_p1;
    ap_return_19 <= res_19_V_write_assi_2_fu_636_p1;
    ap_return_2 <= res_2_V_write_assig_3_fu_262_p1;
    ap_return_20 <= res_20_V_write_assi_2_fu_658_p1;
    ap_return_21 <= res_21_V_write_assi_1_fu_680_p1;
    ap_return_3 <= res_3_V_write_assig_3_fu_284_p1;
    ap_return_4 <= res_4_V_write_assig_3_fu_306_p1;
    ap_return_5 <= res_5_V_write_assig_3_fu_328_p1;
    ap_return_6 <= res_6_V_write_assig_3_fu_350_p1;
    ap_return_7 <= res_7_V_write_assig_3_fu_372_p1;
    ap_return_8 <= res_8_V_write_assig_2_fu_394_p1;
    ap_return_9 <= res_9_V_write_assig_2_fu_416_p1;
    res_0_V_write_assig_3_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_0_V_write_assig_fu_210_p3),17));
    res_0_V_write_assig_fu_210_p3 <= 
        tmp_38_fu_206_p1 when (tmp_3_fu_200_p2(0) = '1') else 
        ap_const_lv16_0;
    res_10_V_write_assi_2_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_10_V_write_assi_fu_430_p3),17));
    res_10_V_write_assi_fu_430_p3 <= 
        tmp_48_fu_426_p1 when (tmp_3_s_fu_420_p2(0) = '1') else 
        ap_const_lv16_0;
    res_11_V_write_assi_2_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_11_V_write_assi_fu_452_p3),17));
    res_11_V_write_assi_fu_452_p3 <= 
        tmp_49_fu_448_p1 when (tmp_3_10_fu_442_p2(0) = '1') else 
        ap_const_lv16_0;
    res_12_V_write_assi_2_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_12_V_write_assi_fu_474_p3),17));
    res_12_V_write_assi_fu_474_p3 <= 
        tmp_50_fu_470_p1 when (tmp_3_11_fu_464_p2(0) = '1') else 
        ap_const_lv16_0;
    res_13_V_write_assi_2_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_13_V_write_assi_fu_496_p3),17));
    res_13_V_write_assi_fu_496_p3 <= 
        tmp_51_fu_492_p1 when (tmp_3_12_fu_486_p2(0) = '1') else 
        ap_const_lv16_0;
    res_14_V_write_assi_2_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_14_V_write_assi_fu_518_p3),17));
    res_14_V_write_assi_fu_518_p3 <= 
        tmp_52_fu_514_p1 when (tmp_3_13_fu_508_p2(0) = '1') else 
        ap_const_lv16_0;
    res_15_V_write_assi_2_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_15_V_write_assi_fu_540_p3),17));
    res_15_V_write_assi_fu_540_p3 <= 
        tmp_53_fu_536_p1 when (tmp_3_14_fu_530_p2(0) = '1') else 
        ap_const_lv16_0;
    res_16_V_write_assi_2_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_16_V_write_assi_fu_562_p3),17));
    res_16_V_write_assi_fu_562_p3 <= 
        tmp_54_fu_558_p1 when (tmp_3_15_fu_552_p2(0) = '1') else 
        ap_const_lv16_0;
    res_17_V_write_assi_2_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_17_V_write_assi_fu_584_p3),17));
    res_17_V_write_assi_fu_584_p3 <= 
        tmp_55_fu_580_p1 when (tmp_3_16_fu_574_p2(0) = '1') else 
        ap_const_lv16_0;
    res_18_V_write_assi_2_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_18_V_write_assi_fu_606_p3),17));
    res_18_V_write_assi_fu_606_p3 <= 
        tmp_56_fu_602_p1 when (tmp_3_17_fu_596_p2(0) = '1') else 
        ap_const_lv16_0;
    res_19_V_write_assi_2_fu_636_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_19_V_write_assi_fu_628_p3),17));
    res_19_V_write_assi_fu_628_p3 <= 
        tmp_57_fu_624_p1 when (tmp_3_18_fu_618_p2(0) = '1') else 
        ap_const_lv16_0;
    res_1_V_write_assig_3_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_1_V_write_assig_fu_232_p3),17));
    res_1_V_write_assig_fu_232_p3 <= 
        tmp_39_fu_228_p1 when (tmp_3_1_fu_222_p2(0) = '1') else 
        ap_const_lv16_0;
    res_20_V_write_assi_2_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_20_V_write_assi_fu_650_p3),17));
    res_20_V_write_assi_fu_650_p3 <= 
        tmp_58_fu_646_p1 when (tmp_3_19_fu_640_p2(0) = '1') else 
        ap_const_lv16_0;
    res_21_V_write_assi_1_fu_680_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_21_V_write_assi_fu_672_p3),17));
    res_21_V_write_assi_fu_672_p3 <= 
        tmp_59_fu_668_p1 when (tmp_3_20_fu_662_p2(0) = '1') else 
        ap_const_lv16_0;
    res_2_V_write_assig_3_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_2_V_write_assig_fu_254_p3),17));
    res_2_V_write_assig_fu_254_p3 <= 
        tmp_40_fu_250_p1 when (tmp_3_2_fu_244_p2(0) = '1') else 
        ap_const_lv16_0;
    res_3_V_write_assig_3_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_3_V_write_assig_fu_276_p3),17));
    res_3_V_write_assig_fu_276_p3 <= 
        tmp_41_fu_272_p1 when (tmp_3_3_fu_266_p2(0) = '1') else 
        ap_const_lv16_0;
    res_4_V_write_assig_3_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_4_V_write_assig_fu_298_p3),17));
    res_4_V_write_assig_fu_298_p3 <= 
        tmp_42_fu_294_p1 when (tmp_3_4_fu_288_p2(0) = '1') else 
        ap_const_lv16_0;
    res_5_V_write_assig_3_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_5_V_write_assig_fu_320_p3),17));
    res_5_V_write_assig_fu_320_p3 <= 
        tmp_43_fu_316_p1 when (tmp_3_5_fu_310_p2(0) = '1') else 
        ap_const_lv16_0;
    res_6_V_write_assig_3_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_6_V_write_assig_fu_342_p3),17));
    res_6_V_write_assig_fu_342_p3 <= 
        tmp_44_fu_338_p1 when (tmp_3_6_fu_332_p2(0) = '1') else 
        ap_const_lv16_0;
    res_7_V_write_assig_3_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_7_V_write_assig_fu_364_p3),17));
    res_7_V_write_assig_fu_364_p3 <= 
        tmp_45_fu_360_p1 when (tmp_3_7_fu_354_p2(0) = '1') else 
        ap_const_lv16_0;
    res_8_V_write_assig_2_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_8_V_write_assig_fu_386_p3),17));
    res_8_V_write_assig_fu_386_p3 <= 
        tmp_46_fu_382_p1 when (tmp_3_8_fu_376_p2(0) = '1') else 
        ap_const_lv16_0;
    res_9_V_write_assig_2_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_9_V_write_assig_fu_408_p3),17));
    res_9_V_write_assig_fu_408_p3 <= 
        tmp_47_fu_404_p1 when (tmp_3_9_fu_398_p2(0) = '1') else 
        ap_const_lv16_0;
    tmp_38_fu_206_p1 <= data_0_V_read(16 - 1 downto 0);
    tmp_39_fu_228_p1 <= data_1_V_read(16 - 1 downto 0);
    tmp_3_10_fu_442_p2 <= "1" when (signed(data_11_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_11_fu_464_p2 <= "1" when (signed(data_12_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_12_fu_486_p2 <= "1" when (signed(data_13_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_13_fu_508_p2 <= "1" when (signed(data_14_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_14_fu_530_p2 <= "1" when (signed(data_15_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_15_fu_552_p2 <= "1" when (signed(data_16_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_16_fu_574_p2 <= "1" when (signed(data_17_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_17_fu_596_p2 <= "1" when (signed(data_18_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_18_fu_618_p2 <= "1" when (signed(data_19_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_19_fu_640_p2 <= "1" when (signed(data_20_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_1_fu_222_p2 <= "1" when (signed(data_1_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_20_fu_662_p2 <= "1" when (signed(data_21_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_2_fu_244_p2 <= "1" when (signed(data_2_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_3_fu_266_p2 <= "1" when (signed(data_3_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_4_fu_288_p2 <= "1" when (signed(data_4_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_5_fu_310_p2 <= "1" when (signed(data_5_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_6_fu_332_p2 <= "1" when (signed(data_6_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_7_fu_354_p2 <= "1" when (signed(data_7_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_8_fu_376_p2 <= "1" when (signed(data_8_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_9_fu_398_p2 <= "1" when (signed(data_9_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_fu_200_p2 <= "1" when (signed(data_0_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_3_s_fu_420_p2 <= "1" when (signed(data_10_V_read) > signed(ap_const_lv17_0)) else "0";
    tmp_40_fu_250_p1 <= data_2_V_read(16 - 1 downto 0);
    tmp_41_fu_272_p1 <= data_3_V_read(16 - 1 downto 0);
    tmp_42_fu_294_p1 <= data_4_V_read(16 - 1 downto 0);
    tmp_43_fu_316_p1 <= data_5_V_read(16 - 1 downto 0);
    tmp_44_fu_338_p1 <= data_6_V_read(16 - 1 downto 0);
    tmp_45_fu_360_p1 <= data_7_V_read(16 - 1 downto 0);
    tmp_46_fu_382_p1 <= data_8_V_read(16 - 1 downto 0);
    tmp_47_fu_404_p1 <= data_9_V_read(16 - 1 downto 0);
    tmp_48_fu_426_p1 <= data_10_V_read(16 - 1 downto 0);
    tmp_49_fu_448_p1 <= data_11_V_read(16 - 1 downto 0);
    tmp_50_fu_470_p1 <= data_12_V_read(16 - 1 downto 0);
    tmp_51_fu_492_p1 <= data_13_V_read(16 - 1 downto 0);
    tmp_52_fu_514_p1 <= data_14_V_read(16 - 1 downto 0);
    tmp_53_fu_536_p1 <= data_15_V_read(16 - 1 downto 0);
    tmp_54_fu_558_p1 <= data_16_V_read(16 - 1 downto 0);
    tmp_55_fu_580_p1 <= data_17_V_read(16 - 1 downto 0);
    tmp_56_fu_602_p1 <= data_18_V_read(16 - 1 downto 0);
    tmp_57_fu_624_p1 <= data_19_V_read(16 - 1 downto 0);
    tmp_58_fu_646_p1 <= data_20_V_read(16 - 1 downto 0);
    tmp_59_fu_668_p1 <= data_21_V_read(16 - 1 downto 0);
end behav;
